<h1 align='center'> 신호 및 시스템 실습 7</h1>

<p style="text-align: right"> 2021.4.29. (목)</p>

<div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름: 장윤제  &nbsp;&nbsp;          학번: 20175334   &nbsp;&nbsp;         학과(전공): 스마트IoT
    
</div>

- Jupyter notebook에 대한 설명은 [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/)을  참고하라.

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)
- Sympy의 복소수 관련 함수는 [sympy.functions.elementary.complexes](https://docs.sympy.org/latest/modules/functions/elementary.html#cbrt)를 참고하라.

* 1차 제출: 5월 1일 (토) 오후 6:00까지 최종본 제출


### 이산 푸리에 급수(DFS: discrete Fourier series)

- 주기가 $N$인 이산 주기 신호의 한 주기 동안의 샘플들을 벡터로 표현
$$\tilde{x}[n] = \tilde{x}[n + kN]$$

$$ \mathbf{x} = \begin{bmatrix} \tilde{x}[0] \\ \tilde{x}[1] \\ \vdots \\ \tilde{x}[N-1] \end{bmatrix}$$

- $N$ 차원 복소 공간의 한 벡터를 표현할 때 사용하는 정규기저 벡터를 변경하는 것




#### 2차원 실수 공간에서 벡터의 표현

- 2차원 실수 공간 $\mathbb{R}^2$에서 $\mathbf{u}_0 = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$,   $\mathbf{u}_1 = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$이라고 하자.

$$\begin{bmatrix} 2 \\ 3 \end{bmatrix} = \begin{bmatrix} 2 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ 3 \end{bmatrix} = 2\begin{bmatrix} 1 \\ 0 \end{bmatrix} + 3 \begin{bmatrix} 0 \\ 1 \end{bmatrix} = 2 \mathbf{u}_0 + 3 \mathbf{u}_1$$

$$\begin{bmatrix} x_0 \\ x_1 \end{bmatrix} = \begin{bmatrix} x_0 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ x_1 \end{bmatrix} = x_0\begin{bmatrix} 1 \\ 0 \end{bmatrix} + x_1 \begin{bmatrix} 0 \\ 1 \end{bmatrix} = x_0 \mathbf{u}_0 + x_1 \mathbf{u}_1$$

- $\mathbf{u}_0$와 $\mathbf{u}_1$은 $\mathbb{R}^2$의 직교 정규 기저 벡터 (orthonormal basis vectors)
  - $\mathbf{u}_0$와 $\mathbf{u}_1$은 서로 직교
  - $|\mathbf{u}_0| = \sqrt{1^2 + 0^2} = 1$
  - $|\mathbf{u}_1 | = \sqrt{0^2 + 1^2} = 1$

<div class="alert alert-block alert-success">

#### 2차원 벡터의 내적

2차원 실수 공간 $\mathbb{R}^2$의 두 벡터 $\mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \end{bmatrix}$과 $\mathbf{y} = \begin{bmatrix} y_0 \\ y_1 \end{bmatrix}$의 내적은 다음과 같이 정의한다.

$$\left\langle \mathbf{x}, \mathbf{y} \right\rangle = \left\langle \begin{bmatrix} x_0 \\ x_1 \end{bmatrix}, \begin{bmatrix} y_0 \\ y_1 \end{bmatrix} \right\rangle = x_0y_0 + x_1 y_1$$
</div>

#### 벡터의 내적의 기하학적 의미

$$\left\langle \mathbf{x}, \mathbf{y} \right\rangle = |\mathbf{x}| \; |\mathbf{y}| \cos\theta,$$
여기에서 $\theta$는 두 벡터가 이루는 각

- 두 벡터가 직교하면, $\theta = \frac{\pi}{2}$ 또는 $\theta = \frac{3\pi}{2}$이고  $\cos \frac{\pi}{2} = 0$이고 $\cos  \frac{3\pi}{2} =0$이므로, 직교하는 두 벡터의 내적은 0

#### 벡터의 크기

$$| \mathbf{x} | = \sqrt{x_0^2 + x_1^2} = \sqrt{\left\langle \mathbf{x}, \mathbf{x} \right\rangle} $$


#### 2차원 실수 공간의 직교 정규 기저 벡터 $\mathbf{u}_0, \mathbf{u}_1$

-  $ \left\langle \mathbf{u}_0, \mathbf{u}_0 \right\rangle = \left\langle \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 1 \\ 0 \end{bmatrix} \right\rangle = 1\cdot 1 + 0 \cdot 0 = 1$ 

<br>

-  $ \left\langle \mathbf{u}_0, \mathbf{u}_1 \right\rangle = \left\langle \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\rangle = 1\cdot 0 + 0 \cdot 1 = 0$

<br>

-  $ \left\langle \mathbf{u}_1, \mathbf{u}_0 \right\rangle = \left\langle \begin{bmatrix} 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ 0 \end{bmatrix} \right\rangle = 0\cdot 1 + 1 \cdot 0 = 0$

<br>

-  $ \left\langle \mathbf{u}_1, \mathbf{u}_1 \right\rangle = \left\langle \begin{bmatrix} 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\rangle = 0\cdot 0 + 1 \cdot 1 = 1$



- $\mathbf{u}_0$와 $\mathbf{u}_1$은 $\mathbb{R}^2$의 직교 정규 기저 벡터 (orthonormal basis vectors)
  - $\mathbf{u}_0$와 $\mathbf{u}_1$은 서로 직교
  - $|\mathbf{u}_0| = \sqrt{1} = 1$
  - $|\mathbf{u}_1 | = \sqrt{1} = 1$

#### 직교 정규 기저 벡터를 이용한 벡터의 표현


$$\begin{bmatrix} 2 \\ 3 \end{bmatrix} = \begin{bmatrix} 2 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ 3 \end{bmatrix} = 2\begin{bmatrix} 1 \\ 0 \end{bmatrix} + 3 \begin{bmatrix} 0 \\ 1 \end{bmatrix} = 2 \mathbf{u}_0 + 3 \mathbf{u}_1$$

$$\mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} = \begin{bmatrix} x_0 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ x_1 \end{bmatrix} = x_0\begin{bmatrix} 1 \\ 0 \end{bmatrix} + x_1 \begin{bmatrix} 0 \\ 1 \end{bmatrix} = x_0 \mathbf{u}_0 + x_1 \mathbf{u}_1$$

그런데

$<\mathbf{u}_0,  \mathbf{x}> = \left\langle \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} \right\rangle = x_0$, 
$<\mathbf{u}_1,  \mathbf{x}> = \left\langle \begin{bmatrix} 0 \\ 1 \end{bmatrix}, \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} \right\rangle = x_1$이므로,

$$\mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} = x_0 \mathbf{u}_0 + x_1 \mathbf{u}_1 = <\mathbf{u}_0,  \mathbf{x}> \mathbf{u}_0 + <\mathbf{u}_1,  \mathbf{x}> \mathbf{u}_1$$


- 또 다른 직교정규 기저 벡터: $\mathbf{w}_0, \mathbf{w}_1$

$$\mathbf{w}_0 = \begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2}\end{bmatrix}, \;\; \mathbf{w}_1 = \begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2}\end{bmatrix} $$

- 직교
  - $<\mathbf{w}_0, \mathbf{w}_1> = \left\langle \begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix},\begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix} \right\rangle = - \frac{2}{4} + \frac{2}{4} =0, $
  - $<\mathbf{w}_1, \mathbf{w}_0> = \left\langle \begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix},\begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix} \right\rangle = - \frac{2}{4} + \frac{2}{4} =0, $
- 단위 벡터
  - $|\mathbf{w}_0| = \sqrt{<\mathbf{w}_0, \mathbf{w}_0>} = \sqrt{\left\langle \begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix},\begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix} \right\rangle} = \sqrt{ \frac{2}{4} + \frac{2}{4}} =1, $
  - $|\mathbf{w}_1| = \sqrt{<\mathbf{w}_1, \mathbf{w}_1>} = \sqrt{\left\langle \begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix},\begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix} \right\rangle} = \sqrt{ \frac{2}{4} + \frac{2}{4}} =1, $


#### 직교 정규 기저 벡터 $\mathbf{w}_0, \mathbf{w}_1$을 이용한 벡터의 표현


$$\begin{bmatrix} 2 \\ 3 \end{bmatrix} = a \mathbf{w}_0 + b \mathbf{w}_1,$$

$$a = \left\langle\mathbf{w}_0, \begin{bmatrix} 2 \\ 3 \end{bmatrix}\right\rangle = \left\langle \begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix}, \begin{bmatrix} 2 \\ 3 \end{bmatrix} \right\rangle =  \frac{5\sqrt{2}}{2},$$

</br>

$$b = \left\langle\mathbf{w}_1, \begin{bmatrix} 2 \\ 3 \end{bmatrix}\right\rangle = \left\langle \begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix}, \begin{bmatrix} 2 \\ 3 \end{bmatrix} \right\rangle =  \frac{\sqrt{2}}{2},$$

따라서 
$$\begin{bmatrix} 2 \\ 3 \end{bmatrix} = \left\langle\mathbf{w}_0, \begin{bmatrix} 2 \\ 3 \end{bmatrix}\right\rangle \mathbf{w}_0 + \left\langle\mathbf{w}_1, \begin{bmatrix} 2 \\ 3 \end{bmatrix}\right\rangle \mathbf{w}_1 = \frac{5\sqrt{2}}{2} \mathbf{w}_0 + \frac{\sqrt{2}}{2} \mathbf{w}_1,$$

$$\mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} 
= \left\langle\mathbf{u}_0, \mathbf{x} \right\rangle \mathbf{u}_0  + \left\langle\mathbf{u}_1, \mathbf{x} \right\rangle \mathbf{u}_1 
$$

</br>

$$\mathbf{x} = \begin{bmatrix} x_0 \\ x_1 \end{bmatrix} 
= \left\langle\mathbf{w}_0, \mathbf{x} \right\rangle \mathbf{w}_0  + \left\langle\mathbf{w}_1, \mathbf{x} \right\rangle \mathbf{w}_1 
$$

</br>

$$\left\langle\mathbf{w}_0, \mathbf{x} \right\rangle = \left\langle  \begin{bmatrix} \frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix}, \begin{bmatrix} x_0 \\ x_1 \end{bmatrix}\right\rangle = \frac{(x_0+x_1)\sqrt{2}}{2}$$

</br>

$$\left\langle\mathbf{w}_1, \mathbf{x} \right\rangle = \left\langle  \begin{bmatrix} -\frac{\sqrt{2}}{2} \\  \frac{\sqrt{2}}{2} \end{bmatrix}, \begin{bmatrix} x_0 \\ x_1 \end{bmatrix}\right\rangle = \frac{(-x_0+x_1)\sqrt{2}}{2}$$

### 직교 정규 기저 벡터를 이용한 $N$ 차원 실수 벡터의 표현

$\mathbf{u}_0$, $\mathbf{u}_1, \cdots, \mathbf{u}_{N-1}$을 $\mathbb{R}^N$ 공간의 직교 정규 기저 벡터(orthonormal basis vectors)라고 하면, 다음 식이 성립한다.

\begin{align*} \langle\mathbf{u}_i, \mathbf{u}_i\rangle = 1, &\mbox{ for } i=0,1,\cdots,N-1, \\
    \langle\mathbf{u}_i, \mathbf{u}_j\rangle = 0, &\mbox{ for } i \ne j, i, j=0,1,\cdots,N-1, 
\end{align*}

여기에서 $\langle \cdot, \cdot \rangle$는 두 벡터의 내적(inner product)으로 다음과 같이 정의된다.



<div class="alert alert-block alert-success">
  
    
**$N$ 차원 실수 벡터 공간 $\mathbb{R}^N$의 두 벡터 $\mathbf{a}$와 $\mathbf{b}$의 내적**
    
$\mathbf{a}=\begin{bmatrix}a_0& a_1& \cdots& a_{N-1}\end{bmatrix}^\intercal$와 $\mathbf{b}=\begin{bmatrix}b_0& b_1& \cdots& b_{N-1}\end{bmatrix}^\intercal$를 $N$ 차원 실수 벡터 공간 $\mathbb{R}^N$의 두 벡터라 하자. 여기에서 $\intercal$는 행렬의 전치(transpose)를 의미한다. $\mathbf{a}$와 $\mathbf{b}$의 내적은 다음과 같이 정의된다.
        \begin{equation}
        \langle \mathbf{a}, \mathbf{b} \rangle = \mathbf{a}^\intercal\mathbf{b}= {\displaystyle \sum_{i=0}^{N-1} a_i b_i=a_0 b_0 + a_1b_1
            + \cdots + a_{N-1} b_{N-1}}.
        \end{equation}

</div>

In [1]:
import sympy as sym
import IPython.display as disp
import numpy as np

<div class="alert alert-block alert-success">

**예제 5.1**

두 벡터 $\mathbf{a} = \begin{bmatrix}2 & 3 &-1 & 4 \end{bmatrix}^T$와 $\mathbf{b} = \begin{bmatrix}3 & -1 & 2 & 2 \end{bmatrix}^T$의 내적을 구하라.
</div>

$$\langle \mathbf{a}, \mathbf{b} \rangle = \mathbf{a}^\intercal \mathbf{b} = \begin{bmatrix}2 &3 &-1 &4 \end{bmatrix} \begin{bmatrix} 3 \\ -1 \\ 2 \\ 2 \end{bmatrix} = 2\cdot 3 + 3\cdot (-1) + (-1)\cdot 2 + 4\cdot 2 = 9.$$

#### NumPy를 이용한 풀이

In [2]:
a = np.array([2, 3, -1, 4])
b = np.array([3, -1, 2, 2])
np.dot(a, b)

9

In [3]:
a.dot(b)

9

In [4]:
a.shape

(4,)

#### Sympy를 이용한 풀이

In [5]:
a = sym.Matrix([2, 3, -1, 4])    #Matrix로 벡터를 표현
b = sym.Matrix([3, -1, 2, 2])    #np.array와 다른점 shape
a.dot(b)

9

In [6]:
a.shape

(4, 1)

#### 문제 1. 
두 벡터 $\mathbf{a} = \begin{bmatrix}3 & 4  \end{bmatrix}^T$와 $\mathbf{b} = \begin{bmatrix}1 & 2 \end{bmatrix}^T$의 내적을 구하라


In [7]:
a = np.array([3,4])
b = np.array([1,2])
np.dot(a,b)

11

In [8]:
a = sym.Matrix([3,4])
b = sym.Matrix([1,2])
a.dot(b)

11

In [15]:
a.transpose()*b

Matrix([[11]])

#### $\mathbb{R}^N$ 공간에서 임의의 벡터 $\mathbf{x}$의 표현

$$\mathbf{x} = a_0\mathbf{u}_0 + a_1\mathbf{u}_1 + \cdots +  a_{N-1}\mathbf{u}_{N-1}.$$

$$\mathbf{x} = \langle\mathbf{u}_0,\mathbf{x}\rangle\mathbf{u}_0 + \langle \mathbf{u}_1,\mathbf{x}\rangle\mathbf{u}_1 + \cdots +  \langle \mathbf{u}_{N-1},\mathbf{x}\rangle\mathbf{u}_{N-1}$$

$$\begin{bmatrix} 1\\ 2 \\ 3 \\ 4 \\ 5 \end{bmatrix} = 
  \begin{bmatrix} 1\\ 0 \\ 0 \\ 0 \\ 0 \end{bmatrix} 
+ \begin{bmatrix} 0\\ 2 \\ 0 \\ 0 \\ 0 \end{bmatrix} 
+ \begin{bmatrix} 0\\ 0 \\ 3 \\ 0 \\ 0 \end{bmatrix} 
+ \begin{bmatrix} 0\\ 0 \\ 0 \\ 4 \\ 0 \end{bmatrix} 
+ \begin{bmatrix} 0\\ 0 \\ 0 \\ 0 \\ 5 \end{bmatrix} = 
  1\begin{bmatrix} 1\\ 0 \\ 0 \\ 0 \\ 0 \end{bmatrix} 
+ 2\begin{bmatrix} 0\\ 1 \\ 0 \\ 0 \\ 0 \end{bmatrix} 
+ 3\begin{bmatrix} 0\\ 0 \\ 1 \\ 0 \\ 0 \end{bmatrix} 
+ 4\begin{bmatrix} 0\\ 0 \\ 0 \\ 1 \\ 0 \end{bmatrix} 
+ 5\begin{bmatrix} 0\\ 0 \\ 0 \\ 0 \\ 1 \end{bmatrix}
$$

### 기저 벡터의 변경

다음과 같이 정의되는 $\mathbf{u}_0$, $\mathbf{u}_1$, $\mathbf{u}_2$, $\mathbf{u}_3$이 $\mathbb{R}^4$ 공간의 직교 정규 기저 벡터라고 하자.
$$
    \mathbf{u}_0 = \begin{bmatrix}1 \\ 0 \\ 0 \\0\end{bmatrix}, \;\;
    \mathbf{u}_1 = \begin{bmatrix}0 \\ 1 \\ 0 \\0\end{bmatrix}, \;\; 
    \mathbf{u}_2 = \begin{bmatrix}0 \\ 0 \\ 1 \\0\end{bmatrix}, \;\;
    \mathbf{u}_3 = \begin{bmatrix}0 \\ 0 \\ 0 \\1\end{bmatrix}. 
$$

#### 문제 2.
$\mathbf{u}_0, \mathbf{u}_1, \mathbf{u}_2, \mathbf{u}_3$가 직교 정규 기저 벡터인 것을 증명하라.

1. 단위 벡터 (크기가 1)
2. 서로 다른 벡터끼리의 내적 0

In [9]:
import numpy as np
u0 = np.array([1,0,0,0])
u1 = np.array([0,1,0,0])
u2 = np.array([0,0,1,0])
u3 = np.array([0,0,0,1])

In [10]:
print(np.sqrt(np.dot(u0,u0)))    #자기자신을 내적했을때 결과가 1이면 단위벡터이다.
print(np.sqrt(np.dot(u1,u1)))
print(np.sqrt(np.dot(u2,u2)))
print(np.sqrt(np.dot(u3,u3)))

1.0
1.0
1.0
1.0


In [11]:
u = [u0, u1, u2, u3]
for v1 in u:
    for v2 in u:
        print(np.dot(v1, v2), end=' ')
    print()

1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 


In [23]:
#-----------------------------------------------------------------

In [19]:
U = np.diag([1,1,1,1])
U

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
U[0]

array([1, 0, 0, 0])

In [21]:
U[1]

array([0, 1, 0, 0])

In [22]:
for v1_ in U:
    for v2_ in U:
        print(np.dot(v1_, v2_), end=' ')
    print()

1 0 0 0 
0 1 0 0 
0 0 1 0 
0 0 0 1 


$\mathbb{R}^4$ 공간에 존재하는 $\mathbf{x} = \begin{bmatrix}1 \\ 3 \\ 4 \\ -1\end{bmatrix}$는 다음과
같이 표현된다.
$$
\mathbf{x} = \begin{bmatrix}1 \\ 3 \\ 4 \\ -1\end{bmatrix} = 1\mathbf{u}_0 + 3\mathbf{u}_1 + 4\mathbf{u}_2 + (-1)\mathbf{u}_3
$$

In [24]:
x = np.array([1,3,4,-1])

In [29]:
x[0]*u0 + x[1]*u1 + x[2]*u2 + x[3]*u3

array([ 1,  3,  4, -1])

$$\mathbf{x} = \langle\mathbf{u}_0,\mathbf{x}\rangle\mathbf{u}_0 + \langle \mathbf{u}_1,\mathbf{x}\rangle\mathbf{u}_1 + \cdots +  \langle \mathbf{u}_{N-1},\mathbf{x}\rangle\mathbf{u}_{N-1}$$

In [30]:
x

array([ 1,  3,  4, -1])

In [35]:
y = np.dot(u0,x)*u0 + np.dot(u1,x)*u1 + np.dot(u2,x)*u2 + np.dot(u3,x)*u3
print(y)

[ 1  3  4 -1]


또 다른 직교 정규 기저 벡터 $\mathbf{v}_0$, $\mathbf{v}_1$, $\mathbf{v}_2$, $\mathbf{v}_3$을 고려해 보자.
$$
    \mathbf{v}_0 = \begin{bmatrix}\frac{1}{2} \\  \frac{1}{2} \\   \frac{1}{2} \\ \frac{1}{2} \end{bmatrix}, \;\;\; 
    \mathbf{v}_1 = \begin{bmatrix}\frac{1}{2} \\  \frac{1}{2} \\  -\frac{1}{2} \\ -\frac{1}{2}\end{bmatrix}, \;\;\; 
    \mathbf{v}_2 = \begin{bmatrix}\frac{1}{2} \\ -\frac{1}{2} \\  -\frac{1}{2} \\ \frac{1}{2} \end{bmatrix}, \;\;\; 
    \mathbf{v}_3 = \begin{bmatrix}\frac{1}{2} \\ -\frac{1}{2} \\   \frac{1}{2} \\ -\frac{1}{2}\end{bmatrix}
$$

In [36]:
v0 = 0.5*np.array([1, 1, 1, 1])
v1 = 0.5*np.array([1, 1, -1, -1])
v2 = 0.5*np.array([1, -1, -1, 1])
v3 = 0.5*np.array([1, -1, 1, -1])

In [37]:
V = [v0, v1, v2, v3]
for v1_ in V:
    for v2_ in V:
        print(np.dot(v1_, v2_), end='  ')
    print()

1.0  0.0  0.0  0.0  
0.0  1.0  0.0  0.0  
0.0  0.0  1.0  0.0  
0.0  0.0  0.0  1.0  


In [38]:
import sympy as sym
import IPython.display as disp

sv0 = sym.Matrix([1/2, 1/2, 1/2, 1/2])
sv1 = sym.Matrix([1/2, 1/2, -1/2, -1/2])
sv2 = sym.Matrix([1/2, -1/2, -1/2, 1/2])
sv3 = sym.Matrix([1/2, -1/2, 1/2, -1/2])

SV = [sv0, sv1, sv2, sv3]
for sv in SV:
    disp.display(sv.dot(sv))


1.00000000000000

1.00000000000000

1.00000000000000

1.00000000000000

$X_k = \langle\mathbf{v}_k, \mathbf{x} \rangle, \; k=0, 1, 2,3,$이라고 하자. $X_k$는 다음과 같이 구할 수 있다.

\begin{align}
    X_0 &= \langle\mathbf{v}_0, \mathbf{x} \rangle = 3.5, \\
    X_1 &= \langle\mathbf{v}_1, \mathbf{x} \rangle = 0.5, \\
    X_2 &= \langle\mathbf{v}_2, \mathbf{x} \rangle = -3.5, \\
    X_3 &= \langle\mathbf{v}_3, \mathbf{x} \rangle = 1.5.
\end{align}

In [43]:
x = sym.Matrix([1, 3, 4, -1])

disp.display(sv0.dot(x))
disp.display(sv1.dot(x))
disp.display(sv2.dot(x))
disp.display(sv3.dot(x))

3.50000000000000

0.500000000000000

-3.50000000000000

1.50000000000000

그러면 $\mathbf{x}$를 다음과 같이 쓸 수 있다. 
$$
\mathbf{x} = \begin{bmatrix}1 \\ 3 \\ 4 \\ -1\end{bmatrix} = 3.5\mathbf{v}_0 + 0.5\mathbf{v}_1 + (-3.5)\mathbf{v}_2 + 1.5\mathbf{v}_3.
$$

In [44]:
sv0.dot(x)*sv0 + sv1.dot(x)*sv1 + sv2.dot(x)*sv2 + sv3.dot(x)*sv3

Matrix([
[ 1.0],
[ 3.0],
[ 4.0],
[-1.0]])

$X_k = \langle\mathbf{v}_k, \mathbf{x} \rangle, \; k=0, 1, 2,3,$이라고 하자. $X_k$는 다음과 같이 구할 수 있다.

\begin{align}
    X_0 &= \langle\mathbf{v}_0, \mathbf{x} \rangle = 3.5, \\
    X_1 &= \langle\mathbf{v}_1, \mathbf{x} \rangle = 0.5, \\
    X_2 &= \langle\mathbf{v}_2, \mathbf{x} \rangle = -3.5, \\
    X_3 &= \langle\mathbf{v}_3, \mathbf{x} \rangle = 1.5.
\end{align}

벡터 $\mathbf{X}$를 $\mathbf{X} = \begin{bmatrix}X_0 \\ X_1 \\ X_2 \\ X_3\end{bmatrix}$으로 정의하면, $X_k$를 개별적으로 구하는 대신에 다음과 같이 행렬과 벡터의 곱으로 표현할 수 있다.

$$
\mathbf{X} = \begin{bmatrix}X_0 \\ X_1 \\ X_2 \\ X_3\end{bmatrix} = 
\begin{bmatrix}
\langle\mathbf{v}_0, \mathbf{x} \rangle \\ 
\langle\mathbf{v}_1, \mathbf{x} \rangle \\ 
\langle\mathbf{v}_2, \mathbf{x} \rangle \\ 
\langle\mathbf{v}_3, \mathbf{x} \rangle
\end{bmatrix} =
\begin{bmatrix}
\mathbf{v}_0^\intercal \mathbf{x} \\ 
\mathbf{v}_1^\intercal \mathbf{x} \\ 
\mathbf{v}_2^\intercal \mathbf{x} \\ 
\mathbf{v}_3^\intercal \mathbf{x}
\end{bmatrix} =
\begin{bmatrix}
\mathbf{v}_0^\intercal \\ 
\mathbf{v}_1^\intercal \\ 
\mathbf{v}_2^\intercal \\ 
\mathbf{v}_3^\intercal
\end{bmatrix} 
\mathbf{x}
=
\begin{bmatrix}
\frac{1}{2} & \frac{1}{2}  &\ \frac{1}{2}  & \frac{1}{2} \\
\frac{1}{2} & \frac{1}{2}  &\ -\frac{1}{2} & -\frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} &\ -\frac{1}{2} & \frac{1}{2} \\
\frac{1}{2} & -\frac{1}{2} &\ \frac{1}{2}  & -\frac{1}{2}
\end{bmatrix}
\begin{bmatrix}
1 \\ 3 \\ 4 \\ -1 
\end{bmatrix} =
\begin{bmatrix}
3.5 \\ 0.5 \\ -3.5 \\ 1.5 
\end{bmatrix}
$$

In [45]:
V = sym.Matrix([[1/2, 1/2, 1/2, 1/2],
                [1/2, 1/2, -1/2, -1/2],
                [1/2, -1/2, -1/2, 1/2],
                [1/2, -1/2, 1/2, -1/2]])
V

Matrix([
[0.5,  0.5,  0.5,  0.5],
[0.5,  0.5, -0.5, -0.5],
[0.5, -0.5, -0.5,  0.5],
[0.5, -0.5,  0.5, -0.5]])

In [46]:
X = V*x
disp.display(X)

Matrix([
[ 3.5],
[ 0.5],
[-3.5],
[ 1.5]])

In [47]:
sym.Inverse(V)*X

Matrix([
[ 1.0],
[ 3.0],
[ 4.0],
[-1.0]])

In [51]:
V*X    #주파수영역에서 시간영역으로

Matrix([
[ 1.0],
[ 3.0],
[ 4.0],
[-1.0]])

In [54]:
#----------------------------------------------------------

In [52]:
import numpy as np
V = 0.5* np.array( [[1., 1., 1., 1.,],
                    [1., 1., -1., -1.],
                    [1., -1., -1., 1.],
                    [1., -1., 1., -1.]])
x = np.array([1., 3., 4., -1.])
np.dot(V,x)

array([ 3.5,  0.5, -3.5,  1.5])

In [53]:
V@x

array([ 3.5,  0.5, -3.5,  1.5])

<div class="alert alert-block alert-success">

**예제 5.1**

$\mathbb{R}^2$ 공간의 한 점 $\mathbf{x}=\begin{bmatrix}3 \\ 4 \end{bmatrix}=3\mathbf{u}_0 + 4\mathbf{u}_1=3\begin{bmatrix}1 \\ 0 \end{bmatrix}+4\begin{bmatrix}0 \\ 1 \end{bmatrix}$를 $\mathbf{w}_0=\begin{bmatrix}\frac{\sqrt{2}}{2} \\ \frac{\sqrt{2}}{2}\end{bmatrix}$와 $\mathbf{w}_1=\begin{bmatrix}-\frac{\sqrt{2}}{2} \\ \frac{\sqrt{2}}{2}\end{bmatrix}$의 선형 결합, 즉 $\mathbf{x}=b_0\mathbf{w}_0 + b_1\mathbf{w}_1$의 형태로 바꾸려고 한다. $b_0$과 $b_1$의 값을 각각 구하라.
</div>

$$        b_0 = {\displaystyle \langle\mathbf{w}_0,  \mathbf{x}\rangle } %\\[3mm]
    = {\displaystyle  \begin{bmatrix}\frac{\sqrt{2}}{2}&\frac{\sqrt{2}}{2}\end{bmatrix} \begin{bmatrix}3 \\ 4\end{bmatrix}}  %\\[3mm]
    = {\displaystyle \frac{3\sqrt{2}}{2} + \frac{4\sqrt{2}}{2} } %\\[3mm]
    = {\displaystyle \frac{7\sqrt{2}}{2}},
$$

$$  b_1 = {\displaystyle \langle\mathbf{w}_1,  \mathbf{x}\rangle } %\\[3mm]
    = {\displaystyle  \begin{bmatrix}-\frac{\sqrt{2}}{2}&\frac{\sqrt{2}}{2}\end{bmatrix} \begin{bmatrix}3 \\ 4\end{bmatrix}}  %\\[3mm]
    = {\displaystyle -\frac{3\sqrt{2}}{2} + \frac{4\sqrt{2}}{2} } %\\[3mm]
    = {\displaystyle \frac{\sqrt{2}}{2}},
$$

In [55]:
x = np.array([3, 4])
w0 = np.array([np.sqrt(2)/2, np.sqrt(2)/2])
w1 = np.array([-np.sqrt(2)/2, np.sqrt(2)/2])
b0 = np.dot(w0, x)
b1 = np.dot(w1, x)
print(b0)
print(b1)
print(7*np.sqrt(2)/2)
print(np.sqrt(2)/2)

4.949747468305834
0.7071067811865475
4.949747468305833
0.7071067811865476


In [56]:
sx =sym.Matrix([3, 4])
sw0 = sym.Matrix([sym.sqrt(2)/2, sym.sqrt(2)/2])
sw1 = sym.Matrix([-sym.sqrt(2)/2, sym.sqrt(2)/2])
sb0 = sw0.dot(sx) 
sb1 = sw1.dot(sx) 
disp.display(sb0)
disp.display(sb1)

7*sqrt(2)/2

sqrt(2)/2

### 직교 정규 기저 벡터를 이용한 $N$ 차원 복소 벡터의 표현

- 2차원 복소벡터의 예
$$
\begin{bmatrix} 1+ 2j \\ -2 - 3j \end{bmatrix} 
= \begin{bmatrix} 1+ 2j \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ -2 - 3j \end{bmatrix}
= (1+ 2j)\begin{bmatrix} 1 \\ 0 \end{bmatrix} + (-2 - 3j)\begin{bmatrix} 0 \\ 1 \end{bmatrix}
= (1+ 2j)\mathbf{u}_0  + (-2 - 3j)\mathbf{u}_1 $$

$\mathbb{R}^N$ 공간과 마찬가지로 $\mathbb{C}^N$ 공간에도 $\mathbf{u}_0$, $\cdots$, $\mathbf{u}_{N-1}$ 외에도 수많은 직교 정규 기저 벡터들이 존재한다. 

$N$ 개의 벡터 $\mathbf{w}_0$, $\cdots$, $\mathbf{w}_{N-1}$도 직교 정규 기저 벡터라고 하면, $\mathbf{x}$를 다음과 같이 표현할 수도 있다.
\begin{equation} \begin{array}{ll}
\mathbf{x} &= \langle\mathbf{u}_0, \mathbf{x} \rangle\mathbf{u}_0 +
\cdots + \langle\mathbf{u}_{N-1}, \mathbf{x}\rangle\mathbf{u}_{N-1} \\
&= \langle\mathbf{w}_0, \mathbf{x}\rangle\mathbf{w}_0 + \cdots +
\langle\mathbf{w}_{N-1}, \mathbf{x}\rangle\mathbf{w}_{N-1}.
\end{array}
\label{x-in-v1-vN}
\end{equation}

$\mathbb{C}^N$ 공간의 두 벡터 $\mathbf{a}$와 $\mathbf{b}$의 내적은 다음과 같이 정의된다.
\begin{equation}
\langle \mathbf{a}, \mathbf{b} \rangle = {\mathbf{a}^\ast}^\intercal\mathbf{b}= {\displaystyle \sum_{i=0}^{N-1} a_i^\ast b_i=a_0^\ast b_0 + a_1^\ast b_1
    + \cdots + a_{N-1}^\ast b_{N-1}},
\end{equation}
여기에서 $^\ast$는 복소수의 공액(complex conjugate)을 의미한다.

**예제 5.4** 다음 벡터들이 $\mathbb{C}^4$ 공간의 직교 정규 기저 벡터들이 되는 것을 확인하라.

$$
\mathbf{w}_0 = \frac{1}{2} \begin{bmatrix}1 \\ 1 \\ 1 \\ 1 \end{bmatrix}, \;\; 
\mathbf{w}_1 = \frac{1}{2} \begin{bmatrix}1 \\ j \\ -1 \\ -j \end{bmatrix} \;\; 
\mathbf{w}_2 = \frac{1}{2} \begin{bmatrix}1 \\ -1 \\ 1 \\ -1 \end{bmatrix} \;\; 
\mathbf{w}_3 = \frac{1}{2} \begin{bmatrix}1 \\ -j \\ -1 \\ j \end{bmatrix}
$$

1. 단위 벡터 증명

 \begin{align*} 
        \langle\mathbf{w}_0,\mathbf{w}_0\rangle &=  {\mathbf{w}_0^\ast}^\intercal \mathbf{w}_0= \frac{1}{4}\begin{bmatrix}1 & 1 & 1 & 1 \end{bmatrix}\begin{bmatrix}1 \\ 1 \\ 1 \\ 1 \end{bmatrix}=\frac{1}{4}(1+1+1+1)=1, \\[3mm]
        \langle\mathbf{w}_1,\mathbf{w}_1\rangle &=  {\mathbf{w}_1^\ast}^\intercal \mathbf{w}_1= \frac{1}{4}\begin{bmatrix}1 & -j & -1 & j \end{bmatrix}\begin{bmatrix}1 \\ j \\ -1 \\ -j \end{bmatrix}= \frac{1}{4}(1+1+1+1)=1, \\[3mm]
        \langle\mathbf{w}_2,\mathbf{w}_2\rangle &=  {\mathbf{w}_2^\ast}^\intercal \mathbf{w}_2= \frac{1}{4}\begin{bmatrix}1 & -1 & 1 & -1 \end{bmatrix}\begin{bmatrix}1 \\ -1 \\ 1 \\ -1 \end{bmatrix}= \frac{1}{4}(1+1+1+1)=1, \\[3mm]
        \langle\mathbf{w}_3,\mathbf{w}_3\rangle &=  {\mathbf{w}_3^\ast}^\intercal \mathbf{w}_3= \frac{1}{4}\begin{bmatrix}1 & j & -1 & -j \end{bmatrix}\begin{bmatrix}1 \\ -j \\ -1 \\ j \end{bmatrix}= \frac{1}{4}(1+1+1+1)=1
\end{align*}

In [13]:
import sympy as sym
import IPython.display as display
w0 = 0.5*sym.Matrix([1, 1, 1, 1])
w1 = 0.5*sym.Matrix([1, sym.I, -1, -sym.I])
w2 = 0.5*sym.Matrix([1, -1, 1, -1])
w3 = 0.5*sym.Matrix([1, -sym.I, -1, sym.I])

In [14]:
disp.display(w1)
disp.display(w1.conjugate())    #conjugate() = 켤레복소수

Matrix([
[   0.5],
[ 0.5*I],
[  -0.5],
[-0.5*I]])

Matrix([
[   0.5],
[-0.5*I],
[  -0.5],
[ 0.5*I]])

In [59]:
disp.display(w0.conjugate().dot(w0))
disp.display(w1.conjugate().dot(w1))
disp.display(w2.conjugate().dot(w2))
disp.display(w3.conjugate().dot(w3))

1.00000000000000

1.00000000000000

1.00000000000000

1.00000000000000

2. 서로 다른 벡터끼리 직교 증명

In [61]:
disp.display(w0.conjugate().dot(w1))
disp.display(w0.conjugate().dot(w2))
disp.display(w0.conjugate().dot(w3))


0

0

0

In [62]:
disp.display(w1.conjugate().dot(w0))
disp.display(w1.conjugate().dot(w2))
disp.display(w1.conjugate().dot(w3))


0

0

0

In [63]:
disp.display(w2.conjugate().dot(w0))
disp.display(w2.conjugate().dot(w1))
disp.display(w2.conjugate().dot(w3))


0

0

0

In [64]:
disp.display([w2.conjugate().dot(w0), w2.conjugate().dot(w1), w2.conjugate().dot(w3) ])


[0, 0, 0]

In [65]:
disp.display(w3.conjugate().dot(w0))
disp.display(w3.conjugate().dot(w1))
disp.display(w3.conjugate().dot(w2))


0

0

0

In [66]:
nw0 = 0.5*np.array([1, 1, 1, 1])
nw1 = 0.5*np.array([1, 1j, -1, -1j])
nw2 = 0.5*np.array([1, -1, 1, -1])
nw3 = 0.5*np.array([1, -1j, -1, 1j])

In [67]:
print(np.dot(nw0.conjugate(), nw0))
print(np.dot(nw1.conjugate(), nw1))
print(np.dot(nw1.conjugate(), nw1))
print(np.dot(nw1.conjugate(), nw1))

1.0
(1+0j)
(1+0j)
(1+0j)


In [68]:
NW = [nw0, nw1, nw2, nw3]
for nw1_ in NW:
    for nw2_ in NW:
        print(np.dot(nw1_.conjugate(), nw2_), end='   ')
    print()

1.0   0j   0.0   0j   
0j   (1+0j)   0j   0j   
0.0   0j   1.0   0j   
0j   0j   0j   (1+0j)   


### $N$ 차원 복소벡터 공간의 직교 정규 기저 벡터

${\displaystyle W_N=e^{-j\frac{2\pi}{N}}}$이라 하면, ${\displaystyle W_N^\ast=e^{j\frac{2\pi}{N}}}$이 된다.

그리고 $\mathbf{w}_0$, $\cdots$, $\mathbf{w}_{N-1}$을 다음과 같이 정의해 보자. 



\begin{align*} 
    \mathbf{w}_0 &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^0& {W_N^\ast}^0&\cdots& {W_N^\ast}^0\end{bmatrix}^\intercal}, \\[3mm]
    \mathbf{w}_1 &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^1& {W_N^\ast}^2& \cdots& {W_N^\ast}^{N-1}\end{bmatrix}^\intercal}, \\
    \;\;\;\; \vdots \\
    \mathbf{w}_k &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^{k}& {W_N^\ast}^{2k}& \cdots& {W_N^\ast}^{(N-1)k}\end{bmatrix}^\intercal},  \\
    \;\;\;\; \vdots \\
    \mathbf{w}_{N-1} &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^{N-1}& {W_N^\ast}^{2(N-1)}& \cdots& {W_N^\ast}^{(N-1)^2}\end{bmatrix}^\intercal},
\end{align*}
그러면 $\mathbf{w}_0$, $\cdots$, $\mathbf{w}_{N-1}$은 직교 정규 기저 벡터들이다.


### 4 차원 복소벡터 공간의 직교 정규 기저 벡터

${\displaystyle W_4=e^{-j\frac{2\pi}{4}}} = -j$

$ W_4^\ast= j$

\begin{align*} 
    \mathbf{w}_0 &=  \frac{1}{\sqrt{4}} \begin{bmatrix}{j}^0& {j}^0& {j}^0& {j}^0\end{bmatrix}^\intercal = \frac{1}{2}\begin{bmatrix}1& 1& 1 & 1\end{bmatrix}^\intercal, \\[3mm]
    \mathbf{w}_1 &=   \frac{1}{\sqrt{4}}\begin{bmatrix}{j}^0& {j}^1& {j}^2& {j}^3\end{bmatrix}^\intercal = \frac{1}{2}\begin{bmatrix}1& j& -1 & -j\end{bmatrix}^\intercal, \\[3mm]
    \mathbf{w}_2 &=   \frac{1}{\sqrt{4}}\begin{bmatrix}{j}^0& {j}^2& {j}^4& {j}^6\end{bmatrix}^\intercal = \frac{1}{2}\begin{bmatrix}1& -1& 1 & -1\end{bmatrix}^\intercal, \\[3mm]
    \mathbf{w}_3 &=   \frac{1}{\sqrt{4}}\begin{bmatrix}{j}^0& {j}^3& {j}^6& {j}^9\end{bmatrix}^\intercal = \frac{1}{2}\begin{bmatrix}1& -j& -1 & j\end{bmatrix}^\intercal, \\[3mm]
\end{align*}


### $N$ 차원 복소벡터 공간의 직교 정규 기저 벡터

${\displaystyle W_N=e^{-j\frac{2\pi}{N}}}$이라 하면, ${\displaystyle W_N^\ast=e^{j\frac{2\pi}{N}}}$이 된다.

그리고 $\mathbf{w}_0$, $\cdots$, $\mathbf{w}_{N-1}$을 다음과 같이 정의해 보자. 



\begin{align*} 
    \mathbf{w}_0 &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^0& {W_N^\ast}^0&\cdots& {W_N^\ast}^0\end{bmatrix}^\intercal}, \\[3mm]
    \mathbf{w}_1 &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^1& {W_N^\ast}^2& \cdots& {W_N^\ast}^{N-1}\end{bmatrix}^\intercal}, \\
    \mathbf{w}_2 &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^2& {W_N^\ast}^2& \cdots& {W_N^\ast}^{2(N-1)}\end{bmatrix}^\intercal}, \\
    \;\;\;\; \vdots \\
    \mathbf{w}_k &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^{k}& {W_N^\ast}^{2k}& \cdots& {W_N^\ast}^{(N-1)k}\end{bmatrix}^\intercal},  \\
    \;\;\;\; \vdots \\
    \mathbf{w}_{N-1} &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^{N-1}& {W_N^\ast}^{2(N-1)}& \cdots& {W_N^\ast}^{(N-1)^2}\end{bmatrix}^\intercal},
\end{align*}
그러면 $\mathbf{w}_0$, $\cdots$, $\mathbf{w}_{N-1}$은 직교 정규 기저 벡터들이다.


### 12 차원 복소벡터 공간의 직교 정규 기저 벡터

${\displaystyle W_N=e^{-j\frac{2\pi}{12}}=e^{-j\frac{\pi}{6}}}$

${\displaystyle W_N^\ast=e^{j\frac{\pi}{6}}}$

\begin{align*} 
    \mathbf{w}_0 &=  {\displaystyle \frac{1}{\sqrt{12}}\begin{bmatrix}1 & 1 & 1 &\cdots& 1 \end{bmatrix}^\intercal}, \\[3mm]
    \mathbf{w}_1 &=  {\displaystyle \frac{1}{\sqrt{12}}\begin{bmatrix}1 & e^{j\frac{\pi}{6}} & e^{j\frac{2\pi}{6}} & \cdots& e^{j\frac{11\pi}{6}}\end{bmatrix}^\intercal}, \\
    \mathbf{w}_2 &=  {\displaystyle \frac{1}{\sqrt{12}}\begin{bmatrix}1 & e^{j\frac{2\pi}{6}}& e^{j\frac{4\pi}{6}}& \cdots& e^{j\frac{22\pi}{6}}\end{bmatrix}^\intercal}, \\
    \;\;\;\; \vdots \\
    \mathbf{w}_k &=  {\displaystyle \frac{1}{\sqrt{12}}\begin{bmatrix}1 & e^{j\frac{ㅏ\pi}{6}}& e^{j\frac{2k\pi}{6}}& \cdots& e^{j\frac{11k\pi}{6}}\end{bmatrix}^\intercal},  \\
    \;\;\;\; \vdots \\
    \mathbf{w}_{11} &=  {\displaystyle \frac{1}{\sqrt{12}}\begin{bmatrix}1 & e^{j\frac{11\pi}{6}}& e^{j\frac{22\pi}{6}}& \cdots& e^{j\frac{11^2\pi}{6}}\end{bmatrix}^\intercal},
\end{align*}


### 이산 푸리에 급수


$\tilde{x}[n]$을 주기가 $N$인 이산 복소 주기 신호라고 하자. 

$$
\tilde{x}[n] = \tilde{x}[n + rN], \;\; r \mbox{는 정수.}
$$

$\tilde{x}[n]$의 한 주기 동안의 샘플들을 모아서 다음과 같이 벡터로 만든 것을 $\mathbf{x}$라고 하자.

$$
\mathbf{x} = \begin{bmatrix}\tilde{x}[0] \\ \tilde{x}[1] \\ \vdots \\ \tilde{x}[N-1]\end{bmatrix}.
$$

이 벡터를 다음과 같이 직교 정규 벡터들의 선형 결합으로 표현할 수 있다.
\begin{equation}
\mathbf{x} = \tilde{x}[0] \mathbf{u}_0 + \cdots + \tilde{x}[N-1] \mathbf{u}_{N-1},
\end{equation}
여기에서 
\begin{equation}
\mathbf{u}_k = \begin{bmatrix}0 \\ \vdots \\ 0 \\ 1 \\  0 \\ \vdots \\ 0\end{bmatrix}
\end{equation}
이다. 즉, $\mathbf{u}_k$는 k 번째 원소만 1이고 나머지는 0인 벡터이다.
이렇게 표현되는 $\mathbf{x}$의 $k$ 번째 원소인 $\tilde{x}[k]$는 시간 영역에서 $k$ 번째 샘플로 이해할 수 있다.


그리고 $\mathbf{x}$를 다음과 같이 또 다른 직교 정규 기저 벡터들의 선형 결합으로도 표현할 수 있다.

$$
\mathbf{x} = \langle \mathbf{w}_0, \mathbf{x} \rangle \mathbf{w}_0 + \cdots + \langle \mathbf{w}_{N-1}, \mathbf{x} \rangle \mathbf{w}_{N-1},
$$

여기에서  $W_N = e^{-j\frac{2\pi}{N}}$이고, $\mathbf{w}_k$는 다음과 같다.
\begin{equation} 
\mathbf{w}_k =  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}{W_N^\ast}^0& {W_N^\ast}^{k}& {W_N^\ast}^{2k}& \cdots& {W_N^\ast}^{(N-1)k}\end{bmatrix}^\intercal}, k=0,1,\cdots,N-1.
\end{equation}

이제 $X_k=\langle \mathbf{w}_k, \mathbf{x} \rangle$라고 하면, $X_k$는 다음과 같이 쓸 수 있다.
\begin{align*}
    X_k &= \langle \mathbf{w}_k, \mathbf{x} \rangle \\[2mm]
    &= {\mathbf{w}_k^\ast}^\intercal \mathbf{x}  \\[2mm]
    &=  {\displaystyle \frac{1}{\sqrt{N}}\begin{bmatrix}W_N^0& W_N^k& W_N^{2k}& \cdots& W_N^{(N-1)k}\end{bmatrix} \begin{bmatrix}\tilde{x}[0]& \tilde{x}[1]& \cdots& \tilde{x}[N-1]\end{bmatrix}^\intercal } \\[4mm]
    &= {\displaystyle \frac{1}{\sqrt{N}}\left(  W_N^0\tilde{x}[0] +W_N^{k}\tilde{x}[1] + \cdots +   W_N^{(N-1)k} \tilde{x}[N-1]\right) }\ \\[4mm]
    %&= \hush{{\displaystyle \frac{1}{\sqrt{N}}\left[ W_N^0\tilde{x}[0] + W_N^{-k}\tilde{x}[1] + \cdots +   W_N^{-(N-1)k}\tilde{x}[N-1]\right] }}\\[4mm] 
    &= {{\displaystyle \frac{1}{\sqrt{N}}\sum_{n=0}^{N-1} W_N^{nk} \tilde{x}[n] }}\\[2mm]
    &= {\displaystyle \frac{1}{\sqrt{N}}\sum_{n=0}^{N-1} e^{-j\frac{2\pi}{N}nk} \tilde{x}[n]. } 
\end{align*}