<h1 align='center'> 신호 및 시스템 실습 3</h1>

<p style="text-align: right"> 2021.3.25 (목)</p>

<div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름: 장윤제  &nbsp;&nbsp;          학번: 20175334   &nbsp;&nbsp;         학과(전공): 스마트 IoT
    
</div>

- Jupyter notebook에 대한 설명은 [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/)을  참고하라

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

* 1차 제출: 오후 3:20까지 실습 시간에 마무리한 것을 제출
* 2차 마감: 1차 제출시 완성하지 못한 학생들은 3월 27일 (토) 오후 6:00까지 최종본 제출


## 채점

| 문제 1| 문제 2| 문제 3| 문제 4| 문제 5| 문제 6| 문제 7| 문제 8| 문제 9| 합계 |
--|--|--|--|--|--|--|--|--|--
 10 | 10 | 10 | 10 | 10 | 10 | 20 | 10 | 10 | 100

# List와 NumPy

- NumPy는 파이썬 프로그래밍 언어를 확장 한 것
- 대규모의 다차원 (숫자) 배열과 행렬 및 이러한 배열에서 작동 할 수있는 높은 수준의 수학 함수 라이브러리를 지원


## 리스트와 NumPy의 ndarray를 이용한 신호와 벡터의 연산

이산시간 신호 $x_1[n] = \{\underset{\uparrow}{1}, 2, 3, 4\}$, $x_2[n] = \{\underset{\uparrow}{2}, 4, 6, 8\}$가 있다고 가정하자.
여기에서 $\uparrow$는 $n=0$ 위치를 나타낸다.

#### 예제 1.

이산시간 신호 $x_1[n] = \{\underset{\uparrow}{1}, 2, 3, 4\}$, $x_2[n] = \{\underset{\uparrow}{2}, 4, 6, 8\}$가 있다고 가정하자.
여기에서 $\uparrow$는 $n=0$ 위치를 나타낸다.

$x[n] = x_1[n] + x_2[n]$을 구하라.

- NumPy의 ndarray를 이용하여 문제 1을 푸는 방법

In [1]:
import numpy as np
x1_nd = np.array([1, 3, 5, 7])
x2_nd = np.array([2, 4, 6, 8])
x = x1_nd + x2_nd
print(x)

[ 3  7 11 15]


#### 문제 1.


리스트를 이용하여 예제 1을 풀어라.


In [1]:
# List를 이용하는 방법
x1 = [1, 3, 5, 7]
x2 = [2, 4, 6, 8]


x = []
for n,m in zip(x1,x2):
    x.append(n+m)
print(x)

[3, 7, 11, 15]


In [2]:
x = []
for n in range(len(x1)):
    x.append(x1[n] + x2[n])
print(x)

[3, 7, 11, 15]


In [5]:
x = [x1[n] + x2[n] for n in range(len(x1))]
x

[3, 7, 11, 15]

In [6]:
x = [n + m for n,m in zip(x1,x2)]
x

[3, 7, 11, 15]

#### 문제 2.
리스트를 이용하여 $y[n] = 3x_1[n] - 2x_2[n]$을 구하라.

In [11]:
# List를 이용하는 방법
x1 = [1, 3, 5, 7]
x2 = [2, 4, 6, 8]
x = [3*n-2*m for n,m in zip(x1,x2)]
x

[-1, 1, 3, 5]

#### 예제 3.
NumPy의 ndarray를 이용하여 벡터 연산하기

두 벡터를 $\mathbf{x}_1 = \begin{bmatrix} 1 \\ 3 \\ 5 \\ 7 \end{bmatrix} = [1 \; 3\; 5\; 7]^T$,
$\mathbf{x}_2 = \begin{bmatrix} 2 \\ 4 \\ 6 \\ 8 \end{bmatrix} = [2 \; 4\; 6\; 8]^T$이라고 하자.

$$3 \mathbf{x}_1 - 2\mathbf{x}_2 = 3\begin{bmatrix} 1 \\ 3 \\ 5 \\ 7 \end{bmatrix} - 2\begin{bmatrix} 2 \\ 4 \\ 6 \\ 8 \end{bmatrix}
= \begin{bmatrix} 3 \\ 9 \\ 15 \\ 21 \end{bmatrix} - \begin{bmatrix} 4 \\ 8 \\ 12 \\ 16 \end{bmatrix}
= \begin{bmatrix} -1 \\ 1 \\ 3 \\ 5 \end{bmatrix}$$

#### 예제 4.

$$< \mathbf{x}_1,  \mathbf{x}_2> =  \mathbf{x}_1^T  \mathbf{x}_2 = [1 \; 3\; 5\; 7] \begin{bmatrix} 2 \\ 4 \\ 6 \\ 8 \end{bmatrix} = (1)(2) + (3)(4) + (5)(6) + (7)(8) = 2 + 12 + 30 + 56 = 100.$$

In [96]:
x1_nd = np.array([1, 3, 5, 7])
x2_nd = np.array([2, 4, 6, 8])
print(x1_nd.shape, x2_nd.shape)   #
x1_nd @ x2_nd

(4,) (4,)


100

In [97]:
x = np.arange(24).reshape(2,3,4)
x.shape,x

((2, 3, 4),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]))

In [98]:
np.matmul(x1_nd, x2_nd)  #1차원배열에선 자동으로 행렬 바꿔서 계산

100

#### 문제 3.  NumPy ndarray 생성 방법에 대한 설명을 적어라.

In [7]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([3, 2, 4])

In [100]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
list(range(0,5,0.1) 

SyntaxError: unexpected EOF while parsing (<ipython-input-19-a16c568e0d2e>, line 1)

**설명**: range()함수는 정수단위만 가능하다

In [14]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

**설명**: \[0,1)범위에서 0.1간격으로 이루어진 배열생성

In [2]:
np.linspace(0, 1, 11)

11

**설명**: \[0,1]범위에서 11개의 일정한 간격을 가진 요소로 이루어진 배열 생성

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

**설명**:  1차원 배열에 1을 5개 넣어줌

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

**설명**: 1차원 배열에 0을 5개 넣어줌

In [18]:
np.empty(5)

array([0., 0., 0., 0., 0.])

**설명**: 5개의 요소를 가지는 배열을 생성, 값을 초기화하지 않음

### 2차원 배열

In [30]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
print(x.sum(axis=1))    #1행씩 덧셈
print(x.sum(axis=0))    #1열씩 덧셈

[ 6 22 38 54]
[24 28 32 36]


### 3차원 배열

In [37]:
x = np.arange(24).reshape(2,3,4)     #0~24를 크게 2개로묶고, 각 묶음 안에서 3개씩 묶고, 각 묶음 안에서 4개씩 묶는다 2*3*4
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [102]:
x.sum()

276

In [39]:
x.sum(axis=0)     #크게 2개로 묶은 행렬의 합

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [35]:
x.sum(axis=1)  #[[3개씩 묶은 행렬의 합],[3개씩 묶은 행렬의 합]]

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [36]:
x.sum(axis=2)  #[[3개씩 묶은 행렬에서 4개씩 묶은 행렬의 합], [3개씩 묶은 행렬에서 4개씩 묶은 행렬의 합]]

array([[ 6, 22, 38],
       [54, 70, 86]])

#### 예제 5. 
행렬 $A$와 $B$가 다음과 같이 주어진다.

$ A = \begin{bmatrix}
            1 & 3 & -1 & 7\\
            -1 & -2 & 3 & 1\\
            2 & -1 & 3 & 1\\
            1 & 3 & 3 & 2\\
\end{bmatrix}, 
B = \begin{bmatrix} 3 & 1 & 2 & -2 \\ 1 & -3 & 4 & -3 \\ 6 & 3 & -2 & -1 \\ 2 & 1 & 3 &1 \end{bmatrix}
$

In [103]:
A = [[1, 3, -1, 7], [-1, -2, 3, 1], [2, -1, 3, 1], [1, 3, 3, 2]]
B = [[3, 1, 2, -2], [1, -3, 4, -3], [6, 3, -2, -1], [2, 1, 3, 1]]

#### 문제 4. 리스트를 이용하여 C = A + B를 계산하라.

In [112]:
c = []

for n in range(4):
    d = []
    for m in range(4):
        d.append(A[n][m] + B[n][m])
    c.append(d)

c

[[4, 4, 1, 5], [0, -5, 7, -2], [8, 2, 1, 0], [3, 4, 6, 3]]

In [59]:
#C0 = [a + b for a, b in zip(A[0]B[0])]

C = [[n + m for n,m in zip(A_, B_)] for A_,B_ in zip(A,B)]
#C = [[n + m for n,m in zip(A_, B_)] for A[n],B[n] in range((len(4)))]

C

[[4, 4, 1, 5], [0, -5, 7, -2], [8, 2, 1, 0], [3, 4, 6, 3]]

#### 예제 6. NumPy ndarray를 이용한 C = A + B 연산

In [44]:
A_nd = np.array(A)
B_nd = np.array(B)
A_nd + B_nd

array([[ 4,  4,  1,  5],
       [ 0, -5,  7, -2],
       [ 8,  2,  1,  0],
       [ 3,  4,  6,  3]])

#### 행렬의 Hadamard product

$${\displaystyle {\begin{bmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{bmatrix}}\circ {\begin{bmatrix}b_{11}&b_{12}&b_{13}\\b_{21}&b_{22}&b_{23}\\b_{31}&b_{32}&b_{33}\end{bmatrix}}={\begin{bmatrix}a_{11}\,b_{11}&a_{12}\,b_{12}&a_{13}\,b_{13}\\a_{21}\,b_{21}&a_{22}\,b_{22}&a_{23}\,b_{23}\\a_{31}\,b_{31}&a_{32}\,b_{32}&a_{33}\,b_{33}\end{bmatrix}}.}$$

In [113]:
A = [[1, 3, -1, 7], [-1, -2, 3, 1], [2, -1, 3, 1], [1, 3, 3, 2]]
B = [[3, 1, 2, -2], [1, -3, 4, -3], [6, 3, -2, -1], [2, 1, 3, 1]]

In [114]:
np.array([[a * b for a, b in zip(A[n], B[n])] for n in range(4)])

array([[  3,   3,  -2, -14],
       [ -1,   6,  12,  -3],
       [ 12,  -3,  -6,  -1],
       [  2,   3,   9,   2]])

In [77]:
A_nd * B_nd

array([[  3,   3,  -2, -14],
       [ -1,   6,  12,  -3],
       [ 12,  -3,  -6,  -1],
       [  2,   3,   9,   2]])

In [78]:
A_nd - B_nd

array([[-2,  2, -3,  9],
       [-2,  1, -1,  4],
       [-4, -4,  5,  2],
       [-1,  2,  0,  1]])

In [79]:
A_nd / B_nd

array([[ 0.33333333,  3.        , -0.5       , -3.5       ],
       [-1.        ,  0.66666667,  0.75      , -0.33333333],
       [ 0.33333333, -0.33333333, -1.5       , -1.        ],
       [ 0.5       ,  3.        ,  1.        ,  2.        ]])

In [80]:
A_nd.shape

(4, 4)

In [51]:
A_nd

array([[ 1,  3, -1,  7],
       [-1, -2,  3,  1],
       [ 2, -1,  3,  1],
       [ 1,  3,  3,  2]])

In [52]:
A_nd.sum()

25

In [53]:
A_nd.sum(axis=0)

array([ 3,  3,  8, 11])

In [54]:
A_nd.sum(axis=1)

array([10,  1,  5,  9])

#### 행렬의 곱

$\mathbf{A}$가 $m \times p$ 행렬이고 $\mathbf{B}$가 $p \times n$ 행렬이라고 하자.

${\displaystyle \mathbf{A} ={\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1p}\\a_{21}&a_{22}&\cdots &a_{2p}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mp}\\\end{bmatrix}},\;\; \mathbf{B} ={\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1n}\\b_{21}&b_{22}&\cdots &b_{2n}\\\vdots &\vdots &\ddots &\vdots \\b_{p1}&b_{n2}&\cdots &b_{pn}\\\end{bmatrix}}}$

행렬곱$ \mathbf {C} = \mathbf {AB}$는 다음과 같이 정의되는 $m  \times n$ 행렬이다.

$${\displaystyle \mathbf {C} ={\begin{bmatrix}c_{11}&c_{12}&\cdots &c_{1n}\\c_{21}&c_{22}&\cdots &c_{2n}\\\vdots &\vdots &\ddots &\vdots \\c_{m1}&c_{m2}&\cdots &c_{mn}\\\end{bmatrix}}},$$
여기에서
$
{\displaystyle c_{rc}=a_{r1}b_{1c}+a_{r2}b_{2c}+\cdots +a_{rp}b_{pc}=\sum _{k=1}^{p}a_{rp}b_{pc}.}
$

이 식을 아래에 다시 적어보자.
$$
{\begin{bmatrix}c_{11}&c_{12}&\cdots &c_{1n}\\c_{21}&c_{22}&\cdots &c_{2n}\\\vdots &\vdots &\ddots &\vdots \\c_{m1}&c_{m2}&\cdots &c_{mn}\\\end{bmatrix}} = {\begin{bmatrix}a_{11}&a_{12}&\cdots &a_{1p}\\a_{21}&a_{22}&\cdots &a_{2p}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\cdots &a_{mp}\\\end{bmatrix}}
{\begin{bmatrix}b_{11}&b_{12}&\cdots &b_{1n}\\b_{21}&b_{22}&\cdots &b_{2n}\\\vdots &\vdots &\ddots &\vdots \\b_{p1}&b_{n2}&\cdots &b_{pn}\\\end{bmatrix}}.
$$

#### 문제 5. 다음 식을 계산하는 프로그램을 작성하라.

$$ C = \begin{bmatrix}
            1 & 3 & -1 & 7\\
            -1 & -2 & 3 & 1\\
\end{bmatrix}
\begin{bmatrix} 3 & 1 \\ 4 & -3 \\ 3 & -1 \\ 1 & 1\end{bmatrix}
$$

[[c00, c01], 


[c10, c11]]

In [232]:
A = np.array([[1, 3, -1, 7], [-1, -2, 3, 1]])
B = np.array([[3, 1], [4, -3], [3, -1], [1, 1]])

In [243]:
C = [[sum([A[m][n]*B[n][k] for n in range((len(A[0])))]) for k in range(2)] for m in range(2)]
C  

[[19, 0], [-1, 3]]

In [160]:
A @ B

array([[19,  0],
       [-1,  3]])

#### 문제 6. 문제 5에서 구한 프로그램을 (m x p) 행렬과  (p x n) 행렬의 곱으로 일반화한 프로그램을 작성하라.

In [5]:
print("m x p 행렬과 p x n 행렬 곱을 계산하려고 한다.")
m = int(input("m을 입력하라: "))
p = int(input("p를 입력하라: "))
n = int(input("n을 입력하라: "))
a = np.random.randint(-5, 5, (m, p))
b = np.random.randint(-5, 5, (p, n))
print(f"{m} x {p} 행렬 \n{a}\n")
print(f"{p} x {n} 행렬 \n{b}\n")

c_mat = [[sum([a[e, w]*b[w, k] for w in range(p)]) for k in range(n)] for e in range(m)]   ##################################


print(c_mat)
print()
print(a@b)

m x p 행렬과 p x n 행렬 곱을 계산하려고 한다.
m을 입력하라: 4
p를 입력하라: 5
n을 입력하라: 6
4 x 5 행렬 
[[ 1 -5  0 -1  2]
 [-1  4  0  3 -4]
 [ 2  0 -1  4  2]
 [ 3 -5 -5  4  1]]

5 x 6 행렬 
[[ 1  2 -3  2  3  1]
 [ 1 -4 -3  1 -2  3]
 [ 2 -4  2  1  0  1]
 [ 0 -5 -1  3 -3 -3]
 [-1 -1  1 -2  2  2]]

[[-6, 25, 15, -10, 20, -7], [7, -29, -16, 19, -28, -6], [-2, -14, -10, 11, -2, -7], [-13, 25, -7, 6, 9, -27]]

[[ -6  25  15 -10  20  -7]
 [  7 -29 -16  19 -28  -6]
 [ -2 -14 -10  11  -2  -7]
 [-13  25  -7   6   9 -27]]


## 문제 7. 
두 배열 a와 b를 입력받아 행렬곱을 반환하는 함수 mat_mul을 작성하라.

In [11]:
def mat_mul(a, b):             ########################################################
    assert a.shape[1] == b.shape[0]
    c = []
    
    for e in range(len(a)):
        d = []
        for k in range(len(b[0])):
            for w in range(len(a[0])):
                d.append(sum([a[e, w]*b[w, k]]))
        c.append(d)
    return c

#### 문제 8. 
mat_mul 함수를 list comprehension을 이용하여 수정한 함수 mat_mul_2를 작성하라.

In [12]:
def mat_mul_2(a, b):
    assert a.shape[1] == b.shape[0]
    c = [[sum([a[e, w]*b[w, k] for w in range(len(a[0]))]) for k in range(len(b[0]))] for e in range(len(a))]
    return c

In [13]:
print("m x p 행렬과 p x n 행렬 곱을 계산하려고 한다.")
m = int(input("m을 입력하라: "))
p = int(input("p를 입력하라: "))
n = int(input("n을 입력하라: "))
a = np.random.randint(-5, 5, (m, p))
b = np.random.randint(-5, 5, (p, n))
print(a)
print(b)
c_mat = mat_mul_2(a, b)
print(c_mat)
c = a@b
print(c)
print(np.matmul(a,b))

m x p 행렬과 p x n 행렬 곱을 계산하려고 한다.
m을 입력하라: 2
p를 입력하라: 3
n을 입력하라: 4
[[-3 -5  2]
 [-1 -3  0]]
[[ 1  0 -5  0]
 [-5  0 -2 -5]
 [ 2 -5  1  2]]
[[26, -10, 27, 29], [14, 0, 11, 15]]
[[ 26 -10  27  29]
 [ 14   0  11  15]]
[[ 26 -10  27  29]
 [ 14   0  11  15]]


#### NumPy 다차원 배열 클래스 ndarray의 주요 attributes

* ndarray.ndim: axes (dimensions)의 수

* ndarray.shape: 차원을 튜플로 표현

* ndarray.size: 원소의 개수

* ndarray.dtype: numpy.int32, numpy.int16, numpy.float64 등

* ndarray.itemsize: 각 원소의 크기를 byte 단위

* ndarray.data: 원소를 포함하고 있는 버퍼. 인덱스를 통해서 접근.

#### NumPy 데이터형

In [3]:
import numpy as np
a = np.array([6, 9, 8, 2])
print("a =", a)
print("a.type =", a.dtype)
b = np.array([6., 9., 8., 2])
print("b = ", b)
print("b.type =", b.dtype)
c = np.array([])
print("c.type =", c.dtype)

a = [6 9 8 2]
a.type = int32
b =  [6. 9. 8. 2.]
b.type = float64
c.type = float64


In [4]:
from sys import getsizeof
f = np.array([1., 2.]) # default np.float64
f16 = np.array([1., 2.], dtype=np.float16)
f32 = np.array([1., 2.], dtype=np.float32)
f.itemsize, f16.itemsize, f32.itemsize

(8, 2, 4)

####  NumPy 정수형의 overflow와 underflow

In [6]:
import numpy as np
a = np.array([100, 200], np.int8)
a

array([100, -56], dtype=int8)

In [5]:
a + a

array([12, 18, 16,  4])

#### 부호없는 3비트 정수형
<img width="300" src="uint3.png" />

#### 부호있는 3비트 정수형 
<img width="300" src="int3.png" />

#### 문제 9.
signed 5-bit 데이터를 사용한 연산에서 다음 물음에 답하라.

1) signed 5-bit 데이터형이 표현할 수 있는 정수의 최댓값과 최솟값을 적어라.

2) 다음 연산 결과를 적어라

  - $8 + 9 = $
  - $-9 - 8 = $
  - $5 - 8 = $
  - $ 4 \times 5 = $
  - $ -3 \times 6 = $